# Generated by Django 4.2.29 on 2026-03-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('income', models.DecimalField(decimal_places=0, max_digits=15)),
                ('score', models.IntegerField()),
                ('status', models.CharField(choices=[('Đã duyệt', 'Đã duyệt'), ('Chờ xử lý', 'Chờ xử lý'), ('Từ chối', 'Từ chối')], max_length=20)),
            ],
        ),
    ]
