# Generated by Django 4.2.29 on 2026-03-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanprofile',
            name='active_loans',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loanprofile',
            name='debt_ratio',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='loanprofile',
            name='evaluated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='loanprofile',
            name='late_payments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loanprofile',
            name='loan_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='loanprofile',
            name='loan_purpose',
            field=models.CharField(default='Tiêu dùng', max_length=100),
        ),
        migrations.AddField(
            model_name='loanprofile',
            name='occupation',
            field=models.CharField(default='Nhân viên văn phòng', max_length=50),
        ),
        migrations.AddField(
            model_name='loanprofile',
            name='work_years',
            field=models.IntegerField(default=1),
        ),
    ]
